# Generated by Django 5.2.1 on 2025-05-12 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 0, 58, 18, 619249), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
